import os
import google_auth_oauthlib.flow
import googleapiclient.discovery
import googleapiclient.errors
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.http import MediaFileUpload

# YouTube Data API upload scope required
scopes = ["https://www.googleapis.com/auth/youtube.upload"]

def get_authenticated_service():
    """
    Authenticates the user using client_secret.json and generates/loads token.json
    for future automated uploads without human intervention.
    """
    creds = None
    # The file token.json stores the user's access and refresh tokens
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', scopes)
        
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("Refreshing YouTube access token...")
            creds.refresh(Request())
        else:
            if not os.path.exists('client_secret.json'):
                print("Error: client_secret.json file not found! Pls add it to the folder.")
                return None
                
            print("No authorization token found. Starting browser login process...")
            print("Please log in with your NEW YouTube Channel account!")
            
            flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(
                'client_secret.json', scopes)
            creds = flow.run_local_server(port=0)
            
        # Save the credentials for the next run (And for GitHub actions)
        with open('token.json', 'w') as token:
            token.write(creds.to_json())
            print("Successfully saved token.json!")

    return googleapiclient.discovery.build("youtube", "v3", credentials=creds)

def upload_video(youtube, file_path, title, description, tags):
    """
    Uploads the video file to YouTube using the authenticated service.
    """
    print(f"Preparing to upload: {file_path}")
    
    body = {
        "snippet": {
            "title": title[:100],  # Title max characters is 100
            "description": description,
            "tags": tags,
            "categoryId": "10" # 10 = Music Category
        },
        "status": {
            "privacyStatus": "public",
            "selfDeclaredMadeForKids": False
        }
    }

    try:
        # Create and upload the video
        insert_request = youtube.videos().insert(
            part=",".join(body.keys()),
            body=body,
            media_body=MediaFileUpload(file_path, chunksize=-1, resumable=True)
        )
        
        print("Uploading to YouTube... This depends on your internet speed.")
        response = insert_request.execute()
        
        print(f"\n✅ Upload Successful! Video ID: {response['id']}")
        print(f"Link: https://youtu.be/{response['id']}\n")
        return True
        
    except googleapiclient.errors.HttpError as e:
        print("A YouTube API error occurred:\n%s" % e.content)
        return False

def run_upload(video_path="downloads/final_video.mp4", song_title="NCS Track", video_type="long"):
    """Main function called by our orchestrator"""
    if not os.path.exists(video_path):
        print(f"Error: Final video not found at {video_path}")
        return False
        
    youtube = get_authenticated_service()
    if not youtube:
        return False
        
    formatted_title = f"{song_title} | Aesthetic Custom Visualizer | No Copyright"
    if video_type == "short":
        formatted_title += " #Shorts"
        
    desc = f"""Listen to {song_title} - Free to use No Copyright Music 🎵
    
Autogenerated with a fully open-source custom Python Video Bot!
- AI generated background upscaled to HD
- Custom Dynamic Cyberpunk Equalizer (Synced to beat)
- Fully Automated Pipeline

#NCS #NoCopyrightSounds #AestheticMusic #Lofi #Cyberpunk"""
    if video_type == "short":
        desc += " #Shorts #YouTubeShorts"

    tags = ["NCS", "No Copyright Sounds", "Aesthetic", "Music Visualizer", "Cyberpunk", "Free Music"]
    if video_type == "short":
        tags.append("Shorts")

    return upload_video(youtube, video_path, formatted_title, desc, tags)

if __name__ == "__main__":
    run_upload()
